"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.db = exports.Commands = exports.Stocks = exports.Items = exports.Users = void 0;
const Users_1 = require("./datastores/Users");
Object.defineProperty(exports, "Users", { enumerable: true, get: function () { return Users_1.Users; } });
const Items_1 = require("./datastores/Items");
Object.defineProperty(exports, "Items", { enumerable: true, get: function () { return Items_1.Items; } });
const Commands_1 = require("./datastores/Commands");
Object.defineProperty(exports, "Commands", { enumerable: true, get: function () { return Commands_1.Commands; } });
const Stocks_1 = require("./datastores/Stocks");
Object.defineProperty(exports, "Stocks", { enumerable: true, get: function () { return Stocks_1.Stocks; } });
const DataStore_1 = require("./datastores/DataStore");
Object.defineProperty(exports, "db", { enumerable: true, get: function () { return DataStore_1.db; } });
