// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from "kysely";

/** Identifier type for public.commands */
export type CommandsCommandId = string & { __brand: "CommandsCommandId" };

/** Represents the table public.commands */
export default interface CommandsTable {
    command_id: ColumnType<
        CommandsCommandId,
        CommandsCommandId,
        CommandsCommandId | null
    >;

    description: ColumnType<string, string | null, string | null>;

    usage: ColumnType<string, string | null, string | null>;

    cooldown_time: ColumnType<number, number | null, number | null>;

    is_admin: ColumnType<boolean, boolean | null, boolean | null>;
}

export type Commands = Selectable<CommandsTable>;

export type NewCommands = Insertable<CommandsTable>;

export type CommandsUpdate = Updateable<CommandsTable>;
