// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.items */
export type ItemsItemId = number & { __brand: 'ItemsItemId' };

/** Represents the table public.items */
export default interface ItemsTable {
  item_id: ColumnType<ItemsItemId, ItemsItemId | null, ItemsItemId | null>;

  name: ColumnType<string, string, string | null>;

  price: ColumnType<number, number | null, number | null>;

  icon: ColumnType<string | null, string | null, string | null>;
}

export type Items = Selectable<ItemsTable>;

export type NewItems = Insertable<ItemsTable>;

export type ItemsUpdate = Updateable<ItemsTable>;
