// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type UsersTable from './Users';
import type ItemsTable from './Items';
import type StocksTable from './Stocks';

export default interface PublicSchema {
  users: UsersTable;

  items: ItemsTable;

  stocks: StocksTable;
}
