// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.runs */
export type RunsRunId = number & { __brand: 'RunsRunId' };

/** Represents the table public.runs */
export default interface RunsTable {
  run_id: ColumnType<RunsRunId, RunsRunId | null, RunsRunId | null>;

  name: ColumnType<string | null, string | null, string | null>;

  description: ColumnType<string | null, string | null, string | null>;

  run_date: ColumnType<string, string | null, string | null>;
}

export type Runs = Selectable<RunsTable>;

export type NewRuns = Insertable<RunsTable>;

export type RunsUpdate = Updateable<RunsTable>;
