// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersUserId } from './Users';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.stocks */
export type StocksCreatedDate = string & { __brand: 'StocksCreatedDate' };

/** Represents the table public.stocks */
export default interface StocksTable {
  stock_id: ColumnType<UsersUserId, UsersUserId, UsersUserId | null>;

  created_date: ColumnType<StocksCreatedDate, StocksCreatedDate | null, StocksCreatedDate | null>;

  price: ColumnType<number, number | null, number | null>;
}

export type Stocks = Selectable<StocksTable>;

export type NewStocks = Insertable<StocksTable>;

export type StocksUpdate = Updateable<StocksTable>;
