// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersUserId } from './Users';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.user_cooldowns */
export type UserCooldownsCommandName = string & { __brand: 'UserCooldownsCommandName' };

/** Represents the table public.user_cooldowns */
export default interface UserCooldownsTable {
  user_id: ColumnType<UsersUserId, UsersUserId, UsersUserId | null>;

  command_name: ColumnType<UserCooldownsCommandName, UserCooldownsCommandName, UserCooldownsCommandName | null>;

  start_date: ColumnType<string, string | null, string | null>;
}

export type UserCooldowns = Selectable<UserCooldownsTable>;

export type NewUserCooldowns = Insertable<UserCooldownsTable>;

export type UserCooldownsUpdate = Updateable<UserCooldownsTable>;
