// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { DateTime } from 'luxon';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.users */
export type UsersId = string & { __brand: 'UsersId' };

/** Represents the table public.users */
export default interface UsersTable {
  id: ColumnType<UsersId, UsersId, UsersId | null>;

  balance: ColumnType<number, number | null, number | null>;

  activity_points: ColumnType<number, number | null, number | null>;

  last_activity_date: ColumnType<DateTime, DateTime | null, DateTime | null>;

  armor: ColumnType<number, number | null, number | null>;
}

export type Users = Selectable<UsersTable>;

export type NewUsers = Insertable<UsersTable>;

export type UsersUpdate = Updateable<UsersTable>;
