// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersUserId } from './Users';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.user_stocks */
export type UserStocksPurchaseDate = string & { __brand: 'UserStocksPurchaseDate' };

/** Represents the table public.user_stocks */
export default interface UserStocksTable {
  user_id: ColumnType<UsersUserId, UsersUserId, UsersUserId>;

  stock_id: ColumnType<UsersUserId, UsersUserId, UsersUserId>;

  purchase_date: ColumnType<UserStocksPurchaseDate, UserStocksPurchaseDate | undefined, UserStocksPurchaseDate>;

  quantity: ColumnType<number, number | undefined, number>;

  purchase_price: ColumnType<number, number | undefined, number>;
}

export type UserStocks = Selectable<UserStocksTable>;

export type NewUserStocks = Insertable<UserStocksTable>;

export type UserStocksUpdate = Updateable<UserStocksTable>;
