// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersUserId, UsersGuildId } from './Users';
import type { ItemsGuildId, ItemsItemId } from './Items';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.user_items */
export default interface UserItemsTable {
  user_id: ColumnType<UsersUserId, UsersUserId, UsersUserId>;

  guild_id: ColumnType<UsersGuildId | ItemsGuildId, UsersGuildId | ItemsGuildId, UsersGuildId | ItemsGuildId>;

  item_id: ColumnType<ItemsItemId, ItemsItemId, ItemsItemId>;

  quantity: ColumnType<number, number | undefined, number>;
}

export type UserItems = Selectable<UserItemsTable>;

export type NewUserItems = Insertable<UserItemsTable>;

export type UserItemsUpdate = Updateable<UserItemsTable>;
