// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersUserId } from "./Users";
import type { ColumnType, Selectable, Insertable, Updateable } from "kysely";

/** Identifier type for public.user_stocks */
export type UserStocksPurchaseDate = string & {
    __brand: "UserStocksPurchaseDate";
};

/** Represents the table public.user_stocks */
export default interface UserStocksTable {
    user_id: ColumnType<UsersUserId, UsersUserId, UsersUserId | null>;

    stock_id: ColumnType<UsersUserId, UsersUserId, UsersUserId | null>;

    purchase_date: ColumnType<
        UserStocksPurchaseDate,
        UserStocksPurchaseDate | null,
        UserStocksPurchaseDate | null
    >;

    quantity: ColumnType<number, number | null, number | null>;

    purchase_price: ColumnType<number, number | null, number | null>;
}

export type UserStocks = Selectable<UserStocksTable>;

export type NewUserStocks = Insertable<UserStocksTable>;

export type UserStocksUpdate = Updateable<UserStocksTable>;
