// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersUserId } from './Users';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.user_stats */
export type UserStatsGuildId = string & { __brand: 'UserStatsGuildId' };

/** Represents the table public.user_stats */
export default interface UserStatsTable {
  user_id: ColumnType<UsersUserId, UsersUserId, UsersUserId>;

  guild_id: ColumnType<UserStatsGuildId, UserStatsGuildId, UserStatsGuildId>;

  balance: ColumnType<number, number | undefined, number>;

  armor: ColumnType<number, number | undefined, number>;
}

export type UserStats = Selectable<UserStatsTable>;

export type NewUserStats = Insertable<UserStatsTable>;

export type UserStatsUpdate = Updateable<UserStatsTable>;
