// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { DateTime } from 'luxon';

/** Identifier type for public.users */
export type UsersId = string & { __brand: 'UsersId' };

/** Represents the table public.users */
export default interface Users {
  id: UsersId;

  balance: number;

  activity_points: number;

  last_active_date: DateTime;

  armor: number;

  role: number | null;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  id: UsersId;

  /** Default value: 0 */
  balance?: number;

  /** Default value: 0 */
  activity_points?: number;

  /** Default value: '2023-10-24 22:45:41.634-04'::timestamp with time zone */
  last_active_date?: DateTime;

  /** Default value: 0 */
  armor?: number;

  role?: number | null;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  id?: UsersId;

  balance?: number;

  activity_points?: number;

  last_active_date?: DateTime;

  armor?: number;

  role?: number | null;
}
