// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersUserId } from "./Users";
import type { ItemsItemId } from "./Items";
import type { ColumnType, Selectable, Insertable, Updateable } from "kysely";

/** Represents the table public.user_items */
export default interface UserItemsTable {
    user_id: ColumnType<UsersUserId, UsersUserId, UsersUserId | null>;

    item_id: ColumnType<ItemsItemId, ItemsItemId, ItemsItemId | null>;

    quantity: ColumnType<number, number | null, number | null>;
}

export type UserItems = Selectable<UserItemsTable>;

export type NewUserItems = Insertable<UserItemsTable>;

export type UserItemsUpdate = Updateable<UserItemsTable>;
