// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersUserId } from './Users';
import type { UserStatsGuildId } from './UserStats';
import type { ColumnType, Selectable } from 'kysely';

/** Represents the view public.users_full */
export default interface UsersFullTable {
  user_id: ColumnType<UsersUserId, never, never>;

  guild_id: ColumnType<UserStatsGuildId, never, never>;

  username: ColumnType<string, never, never>;

  armor: ColumnType<number, never, never>;

  balance: ColumnType<number, never, never>;
}

export type UsersFull = Selectable<UsersFullTable>;
