// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UsersUserId } from "./Users";
import type { CommandsCommandId } from "./Commands";
import type { ColumnType, Selectable, Insertable, Updateable } from "kysely";

/** Represents the table public.user_cooldowns */
export default interface UserCooldownsTable {
    user_id: ColumnType<UsersUserId, UsersUserId, UsersUserId | null>;

    command_id: ColumnType<
        CommandsCommandId,
        CommandsCommandId,
        CommandsCommandId | null
    >;

    start_date: ColumnType<string, string | null, string | null>;
}

export type UserCooldowns = Selectable<UserCooldownsTable>;

export type NewUserCooldowns = Insertable<UserCooldownsTable>;

export type UserCooldownsUpdate = Updateable<UserCooldownsTable>;
